image: registry.sensetime.com/openxrlab/xrsfm@sha256:caad8154b3ec60828ab7d63478256ee1cf36c01b30e2e7a4719e8a08a0e35a05

stages:
  - build
  # - test

build:
  stage: build
  script:
    - mv /xrprimer ../
    - cmake -B build && cmake --build build -j8
  artifacts:
    when: always
    expire_in: 1 hrs
    paths:
      - build/
    

# test:
#   stage: test
#   script:
#     - ./build/roam-pc/player/roam-pc-player -H -c configs/euroc.yaml --tum trajectory.tum euroc:///MH_01_easy/mav0