# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches:
     - alpha_test
    paths-ignore:
      - 'README.md'
      - 'README_CN.md'
      - 'docs/**'

  pull_request:
    paths-ignore:
      - 'README.md'
      - 'README_CN.md'
      - 'docs/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -l {0}
    container:
      image: openxrlab/xrsfm_runtime:ubuntu1804_x64_cu116
      credentials:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PWD}}
    steps:
      - uses: actions/checkout@v2
      - name: Build and install
        run: |
          mv /xrprimer ../
          cmake -B build -D XRSLAM_TEST=ON
          cmake --build build -j4
